# Generated by Django 2.2 on 2022-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=2000)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('type_shipment', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('curent_location', models.CharField(blank=True, max_length=200)),
                ('pickup', models.CharField(max_length=200)),
                ('track_id', models.CharField(default='0', max_length=10)),
                ('width', models.CharField(default='0', max_length=20)),
                ('height', models.CharField(default='0', max_length=20)),
                ('length', models.CharField(default='0', max_length=20)),
                ('weight', models.CharField(default='0', max_length=20)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('date_at', models.DateTimeField(blank=True)),
                ('Delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('body', models.TextField()),
            ],
        ),
    ]
